### ISSUE TITLE
Jasper doesn't re-start after coming back from sleep?

### ISSUE THREAD

**Issue by lestrrat** [jasperapp/jasper#32] opened 2017-03-17 00:37 UTC
![image](https://cloud.githubusercontent.com/assets/49281/24024255/47d92d5a-0af5-11e7-9c99-df577be25892.png)

I used my Mac at home around 6:00 am-ish, closed it to and put it to sleep mode, then came to the office at around 8:40. No activity from Jasper in the last hour :(

**Comment by h13i32maru** [comment] 2017-04-22 01:05
This is a bug, however I do not know a cause in long time😢 

A workaround is a restarting streams. Please check it.
<img width="302" alt="2017-04-22 10 04 06" src="https://cloud.githubusercontent.com/assets/985170/25300108/000598b4-2743-11e7-9739-2032bcb4de59.png">

**Comment by lestrrat** [comment] 2017-04-22 01:09
Maybe you can have a long running timer that periodically checks if the streams area connected?

**Comment by h13i32maru** [comment] 2017-04-22 01:30
It may be possible, however the timer also stop. Because a streams polling is implemented same timer. 

for now, Jasper restart all stream with the following code when power monitor is resumed. But this bug is not solved. I think that the cause is not sleep and power save.

```
  electron.powerMonitor.on('resume', restartAllStreams);
```

I will  continue to inspect this bug.

**Comment by lestrrat** [comment] 2017-04-22 01:33
Booo. darwin--------

**Comment by h13i32maru** [comment] 2018-07-18 13:46
This problem was fixed with v0.6.0 👍

**Closed by h13i32maru** 2018-07-18 13:46 UTC
Labels: Scope: Internal, Status: Consider, Type: Bug
