### ISSUE TITLE
Stop polling after wifi network interruption

### ISSUE THREAD

**Issue by nisshiee** [jasperapp/jasper#21] opened 2016-08-29 10:36 UTC
Sometimes, Jasper stops polling after such situations,
- Wifi network interruption
- Sleep Mac OSX and reopen in other wifi network

Env:
- Jasper: 0.1.2
- Mac OSX: 10.11.4

**Comment by nshiba** [comment] 2016-12-22 06:47
I also happened the same thing.

Env:
- Jasper 0.2.3
- Mac OSX: 10.11.6

**Comment by h13i32maru** [comment] 2017-01-03 11:41
@nisshiee @nshiba Sorry for late replying and thanks.
I know this issue, but I don't know a cause 😢  I will inspect it.

**Comment by gfx** [comment] 2017-01-04 02:30
It's okay if you don't get the cause, but if there's a restart button (or keyboard shortcut) it seems to get better UX.

**Comment by h13i32maru** [comment] 2017-01-04 02:45
> a restart button (or keyboard shortcut)

It is a nice idea! I will try to implement it at next version.

**Comment by h13i32maru** [comment] 2017-01-07 14:51
Please check Jasper v0.2.4-beta.2. This supports to restart streams as a workaround.
https://jasperapp.io/beta.html

**Comment by gfx** [comment] 2017-01-08 02:03
Cool. I'll use it for a while.

**Comment by h13i32maru** [comment] 2018-07-18 13:47
This problem was fixed with v0.6.0 👍

**Closed by h13i32maru** 2018-07-18 13:47 UTC
